# Generated by Django 3.1 on 2020-09-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_categorical_dose_company_dose_formation_kind_name_manufacturing_country_medication_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
