# Generated by Django 3.1 on 2021-01-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200901_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='name',
        ),
        migrations.AlterField(
            model_name='medication',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='categorical_dose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.categorical_dose'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dose',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.formation'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='kind_name',
            field=models.CharField(default='-', max_length=45),
        ),
        migrations.AlterField(
            model_name='medication',
            name='m_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.type'),
        ),
    ]
